server:
  port: 8080

spring:
  profiles:
    active: office
  datasource:
    data: classpath:data-mysql.sql
    initialization-mode: always
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8