server:
  port: 8080

spring:
  profiles:
    active: office
  datasource:
    data: classpath:data-mysql.sql
    initialization-mode: always
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
  messages:
    basename: static/i18n/messages #指定国际化文件路径
  redis:
    database: 0
    host: 192.168.3.65
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
