spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/a1?useUnicode=true&characterEncoding=utf8
      username: pcteam
      password: pcteam11
      initial-size: 2
      max-active: 20
      min-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in_view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true